name: Swift Tests

on:
  push:
    paths:
      - 'desktop/**'
      - '.github/workflows/swift-desktop.yml'
  workflow_dispatch:

jobs:
  test:
    name: Simple Swift Unit Tests
    runs-on: macos-15-large

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Run tests
        timeout-minutes: 5
        run: desktop/test.sh

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: desktop/VibeflowDesktop/TestResults.xcresult
